name: Create Release

on:
  push:
    branches:
      - high

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Dokucraft-TSC-High_BTA-7.1.zip . -i high 

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${GITHUB_REF_NAME}"
          name: "Release ${GITHUB_REF_NAME}"
          body: "Automatic release for ${GITHUB_REF_NAME}"
          draft: false
          prerelease: false
          token: ${{ secrets.TEST_RELEASE }}
          artifacts: Dokucraft-TSC-High_BTA-7.1.zip
