name: Create Light Release

on:
  push:
    branches:
      - light

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Dokucraft-TSC-Light_BTA-7.1.zip . -x .github/\* -x .git/\* -x README.md

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.run_number }}"
          name: "Dokucraft BTA Light Update ${{ env.RELEASE_VERSION }}"
          body: "Automatic release for Dokucraft BTA Light Update ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TEST_RELEASE }}
          artifacts: Dokucraft-TSC-Light_BTA-7.1.zip
