name: Create Light Release

on:
  push:
    branches:
      - light

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Exclude unwanted files
        run: |
          find . -name '.github' -type d -exec rm -rf {} +
          find . -name '.git' -type d -exec rm -rf {} +
          rm -f README.md
          
      - name: Zip files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Dokucraft-TSC-Light_BTA-7.1.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.run_number }}"
          name: "Dokucraft BTA Light Update ${{ env.RELEASE_VERSION }}"
          body: "Automatic release for Dokucraft BTA Light Update ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: Dokucraft-TSC-Light_BTA-7.1.zip
